### ISSUE TITLE
E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present 

### ISSUE THREAD

**Issue by venkatesh-prabu** [niranjan1624/Vuforia-CloudReco-Video#1]
I tried your code Vuforia-CloudReco-Video in GitHub, its was excellent.

While scanning the image I am getting ( E/MediaPlayer-JNI: QCMediaPlayer
mediaplayer NOT present ) issue and the video is not loaded from cloud.

I will be thankful if you help me to fix this issue.

**Comment by niranjandroid** [comment]
Hey Venkatesh,

Thanks for using my code and sorry for later reply. It seems issue is not with my code but the platform you are using. To fix issue you need to check with MediaPlayer you are using. Please check the [link](http://stackoverflow.com/questions/24501086/why-mediaplayer-throws-not-present-error-when-creating-instance-of-it) for more help. Otherwise you can connect with me through my skype(niranjan.iiit) if needed.
